### PR TITLE
Backport PR #73 on branch 1.x (14:54)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #73: 14:54

### CODE REVIEW

**Comment by mpacer** [comment]
merge: no 
close: yes
label: yes

**Comment by Carreau** [comment]
@mapacer can you edit this ?

**Comment by Carreau** [comment]
(and can you edit @meeseeksmachine comment?)

**Comment by mpacer** [comment]
I cannot edit comments that are not mine.

**Pull request closed without merging**
